force-app/main/default/objects/INPC__c/INPC__c.object-meta.xml
<CustomObject>
    <label>INPC</label>
    <nameField>
        <label>INPC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>INPC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INPC__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No aplica</fullName>
            </value>
            <value>
                <fullName>Enero</fullName>
            </value>
            <value>
                <fullName>Febrero</fullName>
            </value>
            <value>
                <fullName>Marzo</fullName>
            </value>
            <value>
                <fullName>Abril</fullName>
            </value>
            <value>
                <fullName>Mayo</fullName>
            </value>
            <value>
                <fullName>Junio</fullName>
            </value>
            <value>
                <fullName>Julio</fullName>
            </value>
            <value>
                <fullName>Agosto</fullName>
            </value>
            <value>
                <fullName>Septiembre</fullName>
            </value>
            <value>
                <fullName>Octubre</fullName>
            </value>
            <value>
                <fullName>Noviembre</fullName>
            </value>
            <value>
                <fullName>Diciembre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INPC__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aniversario 0</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
                <default>true</default>
                <label>2023</label>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INPC__c/recordTypes/INPC.recordType-meta.xml
<RecordType>
    <fullName>INPC</fullName>
    <active>true</active>
    <label>INPC</label>
</RecordType>

force-app/main/default/classes/doit_inpc_inpcTriggerHandler.cls
public with sharing class doit_inpc_inpcTriggerHandler {
    public static void calculateAnualINPC(INPC__c inpc) {
       /* Double inpcSum = 0;
        LIST<INPC__c> fetchINPC = [
                                    SELECT Id, INPC__c 
                                    FROM INPC__c
                                    WHERE Year__c =: inpc.year__c AND Mes__c != null
                                    ];
    
        for( INPC__c a : fetchINPC){
            inpcSum += a.INPC__c;
        }
        INPC__c inpctoUpdate = new INPC__c(id = inpc.id, INPC_Anual__c = inpcSum / fetchINPC.size());
        update inpctoUpdate;*/
    }
}